name: kora-api deploy

on:
  push:
    branches: [ "ra/11" ]
  workflow_dispatch:


env:
  AWS_REGION: ap-northeast-2
  BEANSTALK_APPLICATION_NAME: ${{ secrets.BEANSTALK_APPLICATION_NAME }}
  BEANSTALK_ENV_NAME: ${{ secrets.BEANSTALK_ENV_NAME }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECR_URI: ${{ secrets.ECR_URI }}

jobs:
  deploy:
    name: kora-api deploy with beanstalk & docker
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: set up jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: permission for gradlew
        run: chmod +x ./gradlew
        shell: bash


      - name: build
        run: ./gradlew clean build
        shell: bash


      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}


      - name: login ecr
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      - name: change dockerfile name
        run: |
          cp docker/kora-api.Dockerfile Dockerfile


      - name: build & push image to ecr
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: latest
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI
          docker build -t $ECR_REPOSITORY .
          docker tag $ECR_REPOSITORY:latest $ECR_URI/$ECR_REPOSITORY:latest
          docker push $ECR_URI/$ECR_REPOSITORY:latest

      - name: get current time for version label
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD_HH-mm-ss
          utcOffset: "+09:00"


      - name: generate deploy zip file
        run: |
          mkdir -p deploy         
          cp -r .ebextensions deploy/.ebextensions 
          cp dockerrun/Dockerrun.kora-api.aws.json deploy/Dockerrun.aws.json
          cd deploy && zip -r deploy.zip .

      - name: deploy to beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.BEANSTALK_APPLICATION_NAME }}
          environment_name: ${{ env.BEANSTALK_ENV_NAME }}
          version_label: ${{ env.BEANSTALK_APPLICATION_NAME }}-${{steps.current-time.outputs.formattedTime}}
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy/deploy.zip
          wait_for_environment_recovery: 200
